#include "ThumbnailProvider.h"

#include <QCryptographicHash>
#include <QDateTime>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QImage>
#include <QImageReader>
#include <QPdfDocument>
#include <QRegularExpression>
#include <QRunnable>
#include <QSaveFile>
#include <QStandardPaths>
#include <QThreadPool>

#include <algorithm>

namespace {

// Extensions we try to thumbnail. QImageReader does the real
// check (according to the installed plugins: qwebp, qsvg, qpdf...);
// this list only avoids opening files that are surely not images.
const QSet<QString> kThumbExts = {
    QStringLiteral("png"),  QStringLiteral("jpg"),  QStringLiteral("jpeg"),
    QStringLiteral("webp"), QStringLiteral("gif"),  QStringLiteral("svg"),
    QStringLiteral("bmp"),  QStringLiteral("ico"),  QStringLiteral("tif"),
    QStringLiteral("tiff"), QStringLiteral("pdf"),
};

// --- Cache maintenance policy -----------------------------------
// They are changed here, in a single place. An age policy + a size one.
constexpr qint64 kThumbMaxAgeSecs = 30LL * 24 * 3600;   // 30 days
constexpr qint64 kThumbMaxBytes = 512LL * 1024 * 1024;  // 512 MB

// Is the name a thumbnail of the CURRENT scheme (SHA-1 hex of 40)? It is the
// only pattern that request()/cacheKey writes since Phase B1.
bool isCurrentThumb(const QString &stem) {
  static const QRegularExpression re(QStringLiteral("^[0-9a-f]{40}$"));
  return re.match(stem).hasMatch();
}

// Is it an orphan of the OLD base36 scheme (Utils.simpleHash, <=8 chars)?
// Only .jpg: the image/PDF thumbnails were ALWAYS SHA-1 .png, so
// a non-hex .png is never generated by us and is not touched (safety).
bool isLegacyOrphan(const QString &stem, const QString &ext) {
  static const QRegularExpression re(QStringLiteral("^[0-9a-z]{1,8}$"));
  return ext == QLatin1String("jpg") && !isCurrentThumb(stem) &&
         re.match(stem).hasMatch();
}

// Self-contained prune of `dir` (NOT recursive: entryInfoList only lists the
// direct files, never leaves the folder). Returns the number deleted. It only
// acts on files with Omafiles' name pattern; anything else
// is left intact.
int pruneThumbnailDir(const QString &dir, qint64 maxAgeSecs, qint64 maxBytes) {
  QDir d(dir);
  if (!d.exists())
    return 0;
  const qint64 now = QDateTime::currentSecsSinceEpoch();
  struct Kept {
    QString path;
    qint64 mtime;
    qint64 size;
  };
  QList<Kept> kept;
  int removed = 0;
  const auto infos = d.entryInfoList(QDir::Files | QDir::NoDotAndDotDot);
  for (const QFileInfo &fi : infos) {
    const QString ext = fi.suffix().toLower();
    const QString stem = fi.completeBaseName();
    // (1) Legacy base36 orphan -> just delete (no consumer after B1).
    if (isLegacyOrphan(stem, ext)) {
      if (QFile::remove(fi.absoluteFilePath()))
        ++removed;
      continue;
    }
    // Only thumbnails of the current scheme are managed; the rest is NOT touched.
    if ((ext != QLatin1String("png") && ext != QLatin1String("jpg")) ||
        !isCurrentThumb(stem))
      continue;
    // (2) Age policy.
    if (now - fi.lastModified().toSecsSinceEpoch() >= maxAgeSecs) {
      if (QFile::remove(fi.absoluteFilePath()))
        ++removed;
      continue;
    }
    kept.append({fi.absoluteFilePath(),
                 fi.lastModified().toSecsSinceEpoch(), fi.size()});
  }
  // (3) Size policy: if the total exceeds the limit, delete the
  // oldest ones first until it drops below.
  qint64 total = 0;
  for (const auto &k : kept)
    total += k.size;
  if (total > maxBytes) {
    std::sort(kept.begin(), kept.end(),
              [](const Kept &a, const Kept &b) { return a.mtime < b.mtime; });
    for (const auto &k : kept) {
      if (total <= maxBytes)
        break;
      if (QFile::remove(k.path)) {
        total -= k.size;
        ++removed;
      }
    }
  }
  return removed;
}

} // namespace

ThumbnailProvider::ThumbnailProvider(QObject *parent) : QObject(parent) {
  const QString base =
      QStandardPaths::writableLocation(QStandardPaths::GenericCacheLocation);
  m_cacheDir = base + QStringLiteral("/omafiles/thumbnails");
  QDir().mkpath(m_cacheDir);
  // Maintenance prune once per session, in the background.
  // Skipped under --selfcheck so as not to touch the user's real cache during
  // the tests (the harness validates the policy over a separate temp dir).
  if (!qEnvironmentVariableIsSet("OMAFILES_SELFCHECK"))
    pruneCache();
}

ThumbnailProvider::~ThumbnailProvider() {
  // Cut off the delivery of any in-flight generation: under the lock, mark it
  // dead. A worker that has not delivered yet will see alive=false and will not
  // do invokeMethod(this); one that already holds it blocks us here until it
  // releases (instant delivery, it only posts an event).
  std::lock_guard<std::mutex> lk(m_life->mtx);
  m_life->alive = false;
}

bool ThumbnailProvider::supported(const QString &path) {
  const QString ext = QFileInfo(path).suffix().toLower();
  return kThumbExts.contains(ext);
}

bool ThumbnailProvider::generate(const QString &path, int size,
                                 const QString &outPath) {
  QImage img;

  if (QFileInfo(path).suffix().toLower() == QLatin1String("pdf")) {
    // PDF: first page with QPdfDocument (the qpdf plugin of QImageReader
    // does not render it reliably). Rendered at the thumbnail's
    // resolution, not the native one -> sharp and light.
    QPdfDocument doc;
    if (doc.load(path) != QPdfDocument::Error::None || doc.pageCount() < 1)
      return false;
    QSizeF pts = doc.pagePointSize(0);
    if (pts.isEmpty())
      pts = QSizeF(size, size);
    QSize target(size, size);
    if (pts.width() >= pts.height())
      target.setHeight(qMax(1, qRound(size * pts.height() / pts.width())));
    else
      target.setWidth(qMax(1, qRound(size * pts.width() / pts.height())));
    img = doc.render(0, target);
  } else {
    QImageReader reader(path);
    reader.setAutoTransform(true); // respects the EXIF orientation
    if (!reader.canRead())
      return false;
    // Scale to fit in a square of `size`, only downwards (an
    // already small image is saved at its real size). For SVG, vectorial,
    // setScaledSize renders directly at that size.
    const QSize orig = reader.size();
    if (orig.isValid() && (orig.width() > size || orig.height() > size)) {
      QSize t = orig;
      t.scale(size, size, Qt::KeepAspectRatio);
      reader.setScaledSize(t);
    } else if (!orig.isValid()) {
      reader.setScaledSize(QSize(size, size));
    }
    img = reader.read();
  }

  if (img.isNull())
    return false;

  // Atomic write: temporary file + rename on commit(), so the
  // UI never loads a half-written PNG.
  QSaveFile file(outPath);
  if (!file.open(QIODevice::WriteOnly))
    return false;
  if (!img.save(&file, "PNG")) {
    file.cancelWriting();
    return false;
  }
  return file.commit();
}

QString ThumbnailProvider::request(const QString &path, int size) {
  if (!supported(path))
    return QString();

  const QFileInfo fi(path);
  if (!fi.exists() || !fi.isFile())
    return QString();

  // Key = hash(path|size|bytes|mtime): if the file changes, the
  // key changes and it regenerates (invalidation by path+size+mtime). hashKey()
  // is the canonical scheme shared with the QML paths (see cacheKey()).
  const QString raw = path + QLatin1Char('|') + QString::number(size) +
                      QLatin1Char('|') + QString::number(fi.size()) +
                      QLatin1Char('|') +
                      QString::number(fi.lastModified().toSecsSinceEpoch());
  const QString key = hashKey(raw);
  const QString outPath =
      m_cacheDir + QLatin1Char('/') + key + QStringLiteral(".png");

  if (QFileInfo::exists(outPath))
    return outPath; // cache hit

  if (m_inflight.contains(key))
    return QString(); // already being generated
  m_inflight.insert(key);

  auto life = m_life; // copy of the control block, outlives the singleton
  QThreadPool::globalInstance()->start(QRunnable::create(
      [this, life, path, size, outPath, key]() {
        const bool ok = generate(path, size, outPath);
        // Safe delivery: the destructor takes this same lock, so either we see
        // alive=false (and do not touch the dead singleton) or we hold it and
        // the destructor waits for us to release.
        std::lock_guard<std::mutex> lk(life->mtx);
        if (!life->alive)
          return;
        QMetaObject::invokeMethod(
            this,
            [this, path, outPath, key, ok]() {
              m_inflight.remove(key);
              if (ok)
                emit ready(path, outPath);
            },
            Qt::QueuedConnection);
      }));
  return QString();
}

QString ThumbnailProvider::hashKey(const QString &input) {
  return QString::fromLatin1(
      QCryptographicHash::hash(input.toUtf8(), QCryptographicHash::Sha1)
          .toHex());
}

QString ThumbnailProvider::cacheKey(const QString &input) const {
  return hashKey(input);
}

void ThumbnailProvider::pruneCache() {
  // Captures m_cacheDir by value and uses the free function (not `this`): safe
  // even if the singleton dies while the prune thread is still alive.
  const QString dir = m_cacheDir;
  QThreadPool::globalInstance()->start(QRunnable::create(
      [dir]() { pruneThumbnailDir(dir, kThumbMaxAgeSecs, kThumbMaxBytes); }));
}

int ThumbnailProvider::pruneCacheDir(const QString &dir, qint64 maxAgeSecs,
                                     qint64 maxBytes) const {
  return pruneThumbnailDir(dir, maxAgeSecs, maxBytes);
}
